### ISSUE TITLE
Is the pledge text in the Public Domain?

### ISSUE THREAD

**Issue by jamesdanielmarrsritchey** [breck7/pledge.pub#3]
The pledge text is in the file "readme.scroll", which has been worked on by two people: Stefán Örvar Sigmundsson, and empowerpeople. I haven't found pledges from either of them, and there's no LICENSE file in the repo. Is the pledge text dedicated to the Public Domain?

**Comment by empowerpeople** [comment]
I think we both have signed the pledge and both didn't work on the text of the pledge itself.

**Comment by breck7** [comment]
Everything under breck7/ is public domain :)
